### ISSUE TITLE
Does not work with Dart 2

### ISSUE THREAD

**Issue by rcagantas** [tomwyr/loader-search-bar#3]
```
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because loader_search_bar 0.0.2+3 requires SDK version >=1.19.0 <2.0.0 and no versions of loader_search_bar match >0.0.2+3 <0.1.0, loader_search_bar ^0.0.2+3 is forbidden.

```

**Comment by geraldbaeck** [comment]
Workaround:

```
dependencies:
  loader_search_bar:
    git:
      url: git://github.com/tomwyr/loader-search-bar.git
```
